services:
  postgres:
    image: postgres:trixie
    container_name: psgr
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - dbnet
  wallet:
    build: ./wallet
    image: wallet
    container_name: wallet
    restart: always
    command:  >
      sh -c "
      echo 'Waiting for database...' &&
      while ! nc -z dbps 5432; do sleep 0.1; done &&
      echo 'Database started' &&
      python manage.py migrate &&
      python manage.py loaddata wallet_wallet.json &&
      python manage.py runserver 0.0.0.0:8000
      "
    env_file:
      - .env
    links:
      - "postgres:dbps"
    networks:
      - dbnet
    volumes:
      - ./wallet:/app/www/wallet_rest
    ports:
      - "8000:8000"
    depends_on:
      - postgres

networks:
  dbnet:
    driver: bridge

volumes:
  postgres-data:
