# Generated by Django 5.2.5 on 2025-09-02 10:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account', models.DecimalField(decimal_places=2, default=0, max_digits=52)),
            ],
        ),
    ]
