# Generated by Django 5.2.5 on 2025-08-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.DecimalField(decimal_places=2, default=0, max_digits=52)),
            ],
        ),
    ]
